<?php

global $menu;
$menu = [
    [ 'setup', 'Setup', [
        [ 'start', 'Get Started' ],
        [ 'create', 'Create your First App' ],
        [ 'config', 'Configuration' ],
        [ 'static', 'Static Pages' ],
        [ 'dynamic', 'Dynamic Pages' ],
        [ 'functions', 'Custom Functions' ],
        [ 'components', 'Components' ],
        [ 'assets', 'Styles & Scripts' ],
        [ 'structure', 'Structure of AIO' ],
        [ 'defines', 'Defines' ],
        [ 'database', 'Database' ],
        [ 'multiple', 'Multiple Apps' ],
    ] ],
    [ 'code', 'Code', [
        [ 'intro', 'Introduction' ],
        [ 'reset', 'Reset CSS' ],
        [ 'fonts', 'Fonts' ],
        [ 'micro', 'Micro CSS' ],
        [ 'form', 'Form' ],
        [ 'inputs', 'Inputs' ],
        [ 'art', 'Art CSS', [
            [ 'accordion' ],
            [ 'buttons' ],
            [ 'alerts' ],
            [ 'cards' ],
            [ 'inputs' ],
            [ 'modal' ],
            [ 'steps' ],
            [ 'table' ],
            [ 'tabs' ],
        ] ],
        [ 'party', '3rd Party', [
            [ 'ace', 'Ace' ],
            [ 'barba', 'BarbaJS' ],
            [ 'bot', 'BotJS' ],
            [ 'chart', 'ChartJS' ],
            [ 'clipboard', 'ClipboardJS' ],
            [ 'barcode', 'Barcode' ],
            [ 'maps', 'Google Maps' ],
            [ 'kinetic', 'Kinetic' ],
            [ 'fullpage', 'Fullpage' ],
            [ 'select2', 'Select 2' ],
            [ 'moment', 'Moment JS' ],
            [ 'tilt', 'Tilt JS' ],
        ] ]
    ] ],
    [ 'back', 'Backend', [
        [ 'intro', 'Introduction' ],
        [ 'ajax', 'Ajax' ],
        //[ 'alerts', 'Alerts' ],
        [ 'arrays', 'Arrays' ],
        //[ 'crypto', 'Crypto' ],
        //[ 'database', 'Database' ],
        [ 'elements', 'Elements' ],
        //[ 'uploader', 'File Uploader' ],
        //[ 'translations', 'Translations' ],
        //[ 'options', 'Options' ],
        //[ 'queries', 'Database Queries' ],
        //[ 'functions', 'Functions' ],
        [ 'party', '3rd Party', [
            [ 'email', 'Email' ],
            [ 'cache', 'Fast Cache' ],
            [ 'pay', 'Payment Gateways' ],
            [ 'sms', 'SMS' ],
            [ 'spreadsheet', 'Spreadsheet' ],
        ] ]
    ] ],
    [ 'fun', 'Functions', [
        [ 'db', 'Class DB()' ],
        [ 'access', 'Class ACCESS()' ],
        [ 'alerts', 'Class ALERTS()' ],
        [ 'options', 'Class OPTIONS()' ],
        [ 'cms', 'Class CMS()' ],
        [ 'chat', 'Class CHAT()' ],
        [ 'commerce', 'Class COMMERCE()' ],
        [ 'region', 'Class REGION()' ],
        [ 'backup', 'Class BACKUP()' ],
        [ 'encrypt', 'Encrypt' ],
        [ 'log', 'Error Log' ],
        [ 'translations', 'Translations' ],
        [ 'portal', 'Portal' ],
        [ 'files', 'Media' ],
    ] ],
    [ 'aio', 'Ahead', [
        [ 'future', 'Future of AIO' ],
        [ 'credits', 'Credits' ],
    ] ]
];