<?php
get_comp('head');
render_docs([
    ['h2','Introducing Micro CSS'],
    ['p','Micro CSS lets you style the element directly by writing micro class'],
    ['div.pre mb20','Instead of <pre>text align:right;</pre>, you can just add class <pre>tar</pre>, a short of first characters of inline style'],
    ['p','Micro CSS covers almost all css styling you need in the smallest shortcode possible'],
    ['p','Core objective of micro css is to '],
    '.pb30',
    ['h2','Using Micro CSS'],
    ['p','Simply add \'micro\' to get_style() in your header and you can use imaginable short form of inline style first characters'],
    ['code','get_style(\'micro\');'],
    ['p','Or call \'micro\' along with your other styles'],
    ['code','get_styles([\'other_style\',\'micro\']);'],
    ['p.tip','You must load \'micro\' css later than your other styles'],
    '.pb30',
    ['h2','Positions'],
    'plain',
    ['td',[code('fl'),'float: right']],
    ['td',[code('fr'),'float: left']],
    ['td',[code('fn'),'float: none']],
    ['td',[code('rel'),'position: relative']],
    ['td',[code('abs'),'position: absolute']],
    ['td',[code('fxd'),'position: fixed']],
    ['td',[code('t0'),'top: 0']],
    ['td',[code('r0'),'right: 0']],
    ['td',[code('b0'),'bottom: 0']],
    ['td',[code('l0'),'left: 0']],
    'plain',
    ['p.tip','For the four styles top, right, bottom, left you can append 5, 10, 15 or 20 to get specific offset by pixels, example t5 will give you top: 5px and r20 will style the element right: 20px'],
    ['div.tip','For class="abs r5 t5", Micro CSS will apply styling position: absolute; right: 5px; top: 5px'],
    '.pb30',
    ['h2','Display'],
    'plain',
    ['td',[code('dib'),'display: inline-block']],
    ['td',[code('db'),'display: block']],
    ['td',[code('dn'),'display: none']],
    ['td',[code('di'),'display: inline']],
    ['td',[code('df'),'display: flex']],
    ['td',[code('vat'),'vertical-align: top']],
    ['td',[code('vab'),'vertical-align: bottom']],
    ['td',[code('vam'),'vertical-align: middle']],
    ['td',[code('val'),'vertical-align: baseline']],
    'plain',
    ['p.tip','Display positions can be over written sometimes, you can add !important tag by appending i at the end'],
    'plain',
    ['td',[code('dibi'),'display: inline-block !important']],
    ['td',[code('dbi'),'display: block !important']],
    ['td',[code('dni'),'display: none !important']],
    ['td',[code('dii'),'display: inline !important']],
    ['td',[code('dfi'),'display: flex !important']],
    'plain',
    '.pb30',
    ['h2','Opacity'],
    'plain',
    ['td',[code('op0'),'opacity: 0']],
    ['td',[code('op2'),'opacity: .2']],
    ['td',[code('op3'),'opacity: .3']],
    ['td',[code('op4'),'opacity: .4']],
    ['td',[code('op5'),'opacity: .5']],
    ['td',[code('op6'),'opacity: .6']],
    ['td',[code('op7'),'opacity: .7']],
    ['td',[code('op8'),'opacity: .8']],
    ['td',[code('op9'),'opacity: .9']],
    ['td',[code('op1'),'opacity: 1']],
    'plain',
    '.pb30',
    ['h2','Borders'],
    'plain',
    ['td',[code('br2'),'border-radius: 2px']],
    ['td',[code('br4'),'border-radius: 4px']],
    ['td',[code('br5'),'border-radius: 5px']],
    ['td',[code('br6'),'border-radius: 6px']],
    ['td',[code('br8'),'border-radius: 8px']],
    ['td',[code('br10'),'border-radius: 10px']],
    ['td',[code('br12'),'border-radius: 12px']],
    ['td',[code('br15'),'border-radius: 15px']],
    ['td',[code('br20'),'border-radius: 20px']],
    'plain',
    '.pb30',
    ['h2','Width'],
    'plain',
    ['td',[code('wa'),'width: auto']],
    ['td',[code('wf'),'width: 100%']],
    ['td',[code('ww'),'width: 100%']],
    ['td',[code('w20'),'width: 20px']],
    ['td',[code('w40'),'width: 40px']],
    ['td',[code('w50'),'width: 50px']],
    ['td',[code('w60'),'width: 60px']],
    ['td',[code('w80'),'width: 80px']],
    ['td',[code('w100'),'width: 100px']],
    ['td',[code('w120'),'width: 120px']],
    ['td',[code('w150'),'width: 150px']],
    ['td',[code('w180'),'width: 180px']],
    ['td',[code('w200'),'width: 200px']],
    ['td',[code('w250'),'width: 250px']],
    'plain',
    '.pb30',
    ['h2','Font Sizes'],
    'plain',
    ['td',[code('fz0'),'font-size: 0']],
    ['td',[code('fz_5'),'font-size: .5rem']],
    ['td',[code('fz_8'),'font-size: .8rem']],
    ['td',[code('fz1'),'font-size: 1rem']],
    ['td',[code('fz1_2'),'font-size: 1.2rem']],
    ['td',[code('fz1_4'),'font-size: 1.4rem']],
    ['td',[code('fz1_5'),'font-size: 1.5rem']],
    ['td',[code('fz1_6'),'font-size: 1.6rem']],
    ['td',[code('fz1_8'),'font-size: 1.8rem']],
    ['td',[code('fz2'),'font-size: 2rem']],
    'plain',
    '.pb30',
    ['h2','Line Heights'],
    'plain',
    ['td',[code('lh0'),'line-height: 0']],
    ['td',[code('lh_5'),'line-height: .5rem']],
    ['td',[code('lh_8'),'line-height: .8rem']],
    ['td',[code('lh1'),'line-height: 1rem']],
    ['td',[code('lh1_2'),'line-height: 1.2rem']],
    ['td',[code('lh1_4'),'line-height: 1.4rem']],
    ['td',[code('lh1_5'),'line-height: 1.5rem']],
    ['td',[code('lh1_6'),'line-height: 1.6rem']],
    ['td',[code('lh1_8'),'line-height: 1.8rem']],
    ['td',[code('lh2'),'line-height: 2rem']],
    'plain',
    '.pb30',
    ['h2','Font Weights'],
    'plain',
    ['td',[code('fwl'),code('fl'),'font-weight: lighter']],
    ['td',[code('fwn'),code('fn'),'font-weight: normal']],
    ['td',[code('fwb'),code('fb'),'font-weight: bold']],
    'plain',
    '.pb30',
    ['h2','Text Appearance'],
    'plain',
    ['td',[code('ls0'),'letter-spacing: 0']],
    ['td',[code('ls1'),'letter-spacing: .01rem']],
    ['td',[code('ls2'),'letter-spacing: .02rem']],
    ['td',[code('ls3'),'letter-spacing: .03rem']],
    'plain',
    'plain',
    ['td',[code('ttu'),code('uc'),'text-transform: uppercase']],
    ['td',[code('ttn'),code('nc'),'text-transform: none']],
    'plain',
    'plain',
    ['td',[code('tdu'),'text-decoration: underline']],
    ['td',[code('tdl'),'text-decoration: line-through']],
    ['td',[code('tdn'),'text-decoration: none']],
    ['td',[code('bxs'),'box-shadow: 5px 5px 5px rgba(0,0,0,.06)']],
    ['td',[code('bsn'),'box-shadow: none']],
    'plain',
    '.pb30',
    ['h2','Content Alignments'],
    'plain',
    ['td',[code('tal'),'text-align: left']],
    ['td',[code('tac'),'text-align: center']],
    ['td',[code('tar'),'text-align: right']],
    ['td',[code('jcs'),'justify-content: flex-start']],
    ['td',[code('jcc'),'justify-content: center']],
    ['td',[code('jce'),'justify-content: flex-end']],
    ['td',[code('ais'),'align-items: flex-start']],
    ['td',[code('aic'),'align-items: center']],
    ['td',[code('aie'),'align-items: flex-end']],
    'plain',
    '.pb30',
    ['h2','Cursor'],
    'plain',
    ['td',[code('cp'),'cursor: pointer']],
    ['td',[code('cvr'),'cursor: ns-resize']],
    ['td',[code('chr'),'cursor: ew-resize']],
    ['td',[code('cm'),'cursor: move']],
    ['td',[code('cna'),'cursor: not-allowed']],
    ['td',[code('cl'),'cursor: progress']],
    ['td',[code('ct'),'cursor: text']],
    ['td',[code('czi'),'cursor: zoom-in']],
    ['td',[code('czo'),'cursor: zoom-out']],
    'plain',
    '.pb30',
    ['h2','Margins'],
    ['p.mt20','Margin all around'],
    'plain',
    ['td',[code('ma'),'margin: auto']],
    ['td',[code('m0'),'margin: 0']],
    ['td',[code('m5'),'margin: 5px']],
    ['td',[code('m10'),'margin: 10px']],
    ['td',[code('m15'),'margin: 15px']],
    ['td',[code('m20'),'margin: 20px']],
    ['td',[code('m30'),'margin: 30px']],
    ['td',[code('m40'),'margin: 40px']],
    ['td',[code('m50'),'margin: 50px']],
    ['td',[code('m60'),'margin: 60px']],
    ['td',[code('m70'),'margin: 70px']],
    ['td',[code('m80'),'margin: 80px']],
    ['td',[code('m90'),'margin: 90px']],
    ['td',[code('m100'),'margin: 100px']],
    ['td',[code('m120'),'margin: 120px']],
    ['td',[code('m140'),'margin: 140px']],
    'plain',
    ['p.mt20','Margin horizontally or x-axis (left and right sides)'],
    'plain',
    ['td',[code('mxa'),code('mh0'),'margin-left: 0; margin-right: 0']],
    ['td',[code('mx0'),code('mh0'),'margin-left: 0; margin-right: 0']],
    ['td',[code('mx-10'),code('mh-10'),'margin-left: -10px; margin-right: -10px']],
    ['td',[code('mx10'),code('mh10'),'margin-left: 10px; margin-right: 10px']],
    ['td',[code('mx20'),code('mh20'),'margin-left: 20px; margin-right: 20px']],
    ['td',[code('mx30'),code('mh30'),'margin-left: 30px; margin-right: 30px']],
    ['td',[code('mx40'),code('mh40'),'margin-left: 40px; margin-right: 40px']],
    ['td',[code('mx50'),code('mh50'),'margin-left: 50px; margin-right: 50px']],
    ['td',[code('mx60'),code('mh60'),'margin-left: 60px; margin-right: 60px']],
    ['td',[code('mx70'),code('mh70'),'margin-left: 70px; margin-right: 70px']],
    ['td',[code('mx80'),code('mh80'),'margin-left: 80px; margin-right: 80px']],
    ['td',[code('mx90'),code('mh90'),'margin-left: 90px; margin-right: 90px']],
    ['td',[code('mx100'),code('mh100'),'margin-left: 100px; margin-right: 100px']],
    ['td',[code('mx120'),code('mh120'),'margin-left: 120px; margin-right: 120px']],
    ['td',[code('mx140'),code('mh140'),'margin-left: 140px; margin-right: 140px']],
    'plain',
    ['p.mt20','Margin vertically or y-axis (top and bottom sides)'],
    'plain',
    ['td',[code('mya'),code('mva'),'margin-top: auto; margin-bottom: auto']],
    ['td',[code('my0'),code('mv0'),'margin-top: 0; margin-bottom: 0']],
    ['td',[code('my10'),code('mv10'),'margin-top: 10px; margin-bottom: 10px']],
    ['td',[code('my20'),code('mv20'),'margin-top: 20px; margin-bottom: 20px']],
    ['td',[code('my30'),code('mv30'),'margin-top: 30px; margin-bottom: 30px']],
    ['td',[code('my40'),code('mv40'),'margin-top: 40px; margin-bottom: 40px']],
    ['td',[code('my50'),code('mv50'),'margin-top: 50px; margin-bottom: 50px']],
    ['td',[code('my60'),code('mv60'),'margin-top: 60px; margin-bottom: 60px']],
    ['td',[code('my70'),code('mv70'),'margin-top: 70px; margin-bottom: 70px']],
    ['td',[code('my80'),code('mv80'),'margin-top: 80px; margin-bottom: 80px']],
    ['td',[code('my90'),code('mv90'),'margin-top: 90px; margin-bottom: 90px']],
    ['td',[code('my100'),code('mv100'),'margin-top: 100px; margin-bottom: 100px']],
    ['td',[code('my120'),code('mv120'),'margin-top: 120px; margin-bottom: 120px']],
    ['td',[code('my140'),code('mv140'),'margin-top: 140px; margin-bottom: 140px']],
    'plain',
    ['p.mt20','Margin top'],
    'plain',
    ['td',[code('mta'),'margin-top: auto']],
    ['td',[code('mt0'),'margin-top: 0 !important']],
    ['td',[code('mt5'),'margin-top: 5px']],
    ['td',[code('mt10'),'margin-top: 10px']],
    ['td',[code('mt15'),'margin-top: 15px']],
    ['td',[code('mt20'),'margin-top: 20px']],
    ['td',[code('mt30'),'margin-top: 30px']],
    ['td',[code('mt40'),'margin-top: 40px']],
    ['td',[code('mt60'),'margin-top: 60px']],
    ['td',[code('mt80'),'margin-top: 80px']],
    ['td',[code('mt100'),'margin-top: 100px']],
    'plain',
    ['p.mt20','Margin right'],
    'plain',
    ['td',[code('mra'),'margin-right: auto']],
    ['td',[code('mr0'),'margin-right: 0 !important']],
    ['td',[code('mr5'),'margin-right: 5px']],
    ['td',[code('mr10'),'margin-right: 10px']],
    ['td',[code('mr15'),'margin-right: 15px']],
    ['td',[code('mr20'),'margin-right: 20px']],
    ['td',[code('mr30'),'margin-right: 30px']],
    'plain',
    ['p.mt20','Margin bottom'],
    'plain',
    ['td',[code('mba'),'margin-bottom: auto']],
    ['td',[code('mb0'),'margin-bottom: 0 !important']],
    ['td',[code('mb5'),'margin-bottom: 5px']],
    ['td',[code('mb10'),'margin-bottom: 10px']],
    ['td',[code('mb15'),'margin-bottom: 15px']],
    ['td',[code('mb20'),'margin-bottom: 20px']],
    ['td',[code('mb30'),'margin-bottom: 30px']],
    ['td',[code('mb40'),'margin-bottom: 40px']],
    ['td',[code('mb60'),'margin-bottom: 60px']],
    ['td',[code('mb80'),'margin-bottom: 80px']],
    ['td',[code('mb100'),'margin-bottom: 100px']],
    'plain',
    ['p.mt20','Margin left'],
    'plain',
    ['td',[code('mla'),'margin-left: auto']],
    ['td',[code('ml0'),'margin-left: 0 !important']],
    ['td',[code('ml5'),'margin-left: 5px']],
    ['td',[code('ml10'),'margin-left: 10px']],
    ['td',[code('ml15'),'margin-left: 15px']],
    ['td',[code('ml20'),'margin-left: 20px']],
    ['td',[code('ml30'),'margin-left: 30px']],
    'plain',
    '.pb30',
    ['h2','Paddings'],
    ['p.mt20','Padding all around'],
    'plain',
    ['td',[code('p0'),'padding: 0 !important']],
    ['td',[code('p5'),'padding: 5px']],
    ['td',[code('p10'),'padding: 10px']],
    ['td',[code('p15'),'padding: 15px']],
    ['td',[code('p20'),'padding: 20px']],
    ['td',[code('p30'),'padding: 30px']],
    ['td',[code('p40'),'padding: 40px']],
    ['td',[code('p60'),'padding: 60px']],
    ['td',[code('p80'),'padding: 80px']],
    ['td',[code('p100'),'padding: 100px']],
    'plain',
    ['p.mt20','Padding top'],
    'plain',
    ['td',[code('pt0'),'padding-top: 0 !important']],
    ['td',[code('pt5'),'padding-top: 5px']],
    ['td',[code('pt10'),'padding-top: 10px']],
    ['td',[code('pt15'),'padding-top: 15px']],
    ['td',[code('pt20'),'padding-top: 20px']],
    ['td',[code('pt30'),'padding-top: 30px']],
    ['td',[code('pt40'),'padding-top: 40px']],
    ['td',[code('pt60'),'padding-top: 60px']],
    ['td',[code('pt80'),'padding-top: 80px']],
    ['td',[code('pt100'),'padding-top: 100px']],
    'plain',
    ['p.mt20','Padding right'],
    'plain',
    ['td',[code('pr0'),'padding-right: 0']],
    ['td',[code('pr5'),'padding-right: 5px']],
    ['td',[code('pr10'),'padding-right: 10px']],
    ['td',[code('pr15'),'padding-right: 15px']],
    ['td',[code('pr20'),'padding-right: 20px']],
    'plain',
    ['p.mt20','Padding bottom'],
    'plain',
    ['td',[code('pb0'),'padding-bottom: 0 !important']],
    ['td',[code('pb5'),'padding-bottom: 5px']],
    ['td',[code('pb10'),'padding-bottom: 10px']],
    ['td',[code('pb15'),'padding-bottom: 15px']],
    ['td',[code('pb20'),'padding-bottom: 20px']],
    ['td',[code('pb30'),'padding-bottom: 30px']],
    ['td',[code('pb40'),'padding-bottom: 40px']],
    ['td',[code('pb60'),'padding-bottom: 60px']],
    ['td',[code('pb80'),'padding-bottom: 80px']],
    ['td',[code('pb100'),'padding-bottom: 100px']],
    'plain',
    ['p.mt20','Padding left'],
    'plain',
    ['td',[code('pl0'),'padding-left: 0']],
    ['td',[code('pl5'),'padding-left: 5px']],
    ['td',[code('pl10'),'padding-left: 10px']],
    ['td',[code('pl15'),'padding-left: 15px']],
    ['td',[code('pl20'),'padding-left: 20px']],
    'plain',
]);
docs_nav();
get_comp('foot');