<?php
get_comp('head');
$pages = '<div class="pagination red"><button class="page_link">1</button><button class="page_link">...</button><button class="page_link on">5</button><button class="page_link">...</button><button class="page_link">7</button></div>';
$pages_round = '<div class="pagination blue r"><button class="page_link">1</button><button class="page_link">...</button><button class="page_link on">5</button><button class="page_link">...</button><button class="page_link">7</button></div>';
$pages_split = '<div class="pagination grey split"><button class="page_link">1</button><button class="page_link">...</button><button class="page_link on">5</button><button class="page_link">...</button><button class="page_link">7</button></div>';
render_docs([
    [ 'h1', 'Buttons' ],
    [ 'p', 'Buttons ART give developer quick classes to wide range of buttons varying by color, size and design' ],
    '.pb30',
    [ 'h2', 'Simple Button' ],
    [ 'p', 'You can turn almost any element into button by adding "btn" class or simple use button element' ],
    'plain',
    [ 'td', [ '<button>Click Me</button>', code('<button>Click Me</button>') ] ],
    [ 'td', [ '<div class="btn">Click Me</div>', code('<div class="btn">Click Me</div>') ] ],
    [ 'td', [ '<a href="#" class="btn">Click Me</a>', code('<a href="#" class="btn">Click Me</a>') ] ],
    'plain',
    '.pb30',
    [ 'h2', 'Sizing' ],
    'plain',
    [ 'td', button_code( 'xxs', 'Extra Extra Small' ) ],
    [ 'td', button_code( 'xs', 'Extra Small' ) ],
    [ 'td', button_code( 's', 'Small' ) ],
    [ 'td', button_code( 'm', 'Medium' ) ],
    [ 'td', button_code( 'l', 'Large' ) ],
    [ 'td', button_code( 'xl', 'Extra Large' ) ],
    [ 'td', button_code( 'xxl', 'Extra Extra Large' ) ],
    'plain',
    '.pb30',
    [ 'h2', 'Curved Edges' ],
    'plain',
    [ 'td', button_code( 'r2', 'Round 2px' ) ],
    [ 'td', button_code( 'r5', 'Round 5px' ) ],
    [ 'td', button_code( 'r8', 'Round 8px' ) ],
    [ 'td', button_code( 'r1', 'Round 10px' ) ],
    [ 'td', button_code( 'r', 'Full Round' ) ],
    'plain',
    '.pb30',
    [ 'h2', 'Colors' ],
    'plain',
    [ 'td', button_code( 'red', 'Red Button' ) ],
    [ 'td', button_code( 'blue', 'Blue Button' ) ],
    [ 'td', button_code( 'skyblue', 'Skyblue Button' ) ],
    [ 'td', button_code( 'ocean', 'Ocean Button' ) ],
    [ 'td', button_code( 'silver', 'Silver Button' ) ],
    [ 'td', button_code( 'teal', 'Teal Button' ) ],
    [ 'td', button_code( 'green', 'Green Button' ) ],
    [ 'td', button_code( 'gold', 'Gold Button' ) ],
    [ 'td', button_code( 'grey', 'Grey Button' ) ],
    [ 'td', button_code( 'darkgrey', 'Dark Grey Button' ) ],
    [ 'td', button_code( 'black', 'Black Button' ) ],
    [ 'td', button_code( 'violet', 'Violet Button' ) ],
    [ 'td', button_code( 'orange', 'Orange Button' ) ],
    'plain',
    [ 'p', 'You can just flip fill color to be applied only to border by just adding class "b"' ],
    'plain',
    [ 'td', button_code( 'red b', 'Red Button' ) ],
    [ 'td', button_code( 'blue b', 'Blue Button' ) ],
    [ 'td', button_code( 'skyblue b', 'Skyblue Button' ) ],
    [ 'td', button_code( 'ocean b', 'Ocean Button' ) ],
    [ 'td', button_code( 'silver b', 'Silver Button' ) ],
    [ 'td', button_code( 'teal b', 'Teal Button' ) ],
    [ 'td', button_code( 'green b', 'Green Button' ) ],
    [ 'td', button_code( 'gold b', 'Gold Button' ) ],
    [ 'td', button_code( 'grey b', 'Grey Button' ) ],
    [ 'td', button_code( 'darkgrey b', 'Dark Grey Button' ) ],
    [ 'td', button_code( 'black b', 'Black Button' ) ],
    [ 'td', button_code( 'violet b', 'Violet Button' ) ],
    [ 'td', button_code( 'orange b', 'Orange Button' ) ],
    'plain',
    [ 'p', 'You can add color class to parent wrapper and all child buttons will take that color' ],
    [ 'p', '<div class="blue"><button>Add User</button> <button>Edit User</button></div>' ],
    [ 'code', '<div class="blue"><button>Add User</button> <button>Edit User</button></div>' ],
    [ 'p', 'You can try that with size too' ],
    [ 'p', '<div class="xs"><button>Add User</button> <button>Edit User</button></div>' ],
    [ 'code', '<div class="xs"><button>Add User</button> <button>Edit User</button></div>' ],
    '.pb30',
    [ 'h2', 'Animations' ],
    [ 'p', 'You can add class "load" to button and add element span with class "loader" to create loading animation!' ],
    'plain',
    [ 'td', button_code( 'load', 'Loading... <span class="loader"></span>' ) ],
    'plain',
    [ 'p', 'You can remove the default hover floating animation by adding class "nf"' ],
    'plain',
    [ 'td', button_code( 'nf', 'No Float' ) ],
    'plain',
    [ 'p', 'You can remove the shadow by adding class "bsn"' ],
    'plain',
    [ 'td', button_code( 'bsn', 'Box Shadow None' ) ],
    'plain',
    '.pb30',
    [ 'h2', 'Combinations' ],
    [ 'p', 'You can be as creative as you can by combining above classes to create any type of button' ],
    'plain',
    [ 'td', button_code( 'grey xs bsn r nf', 'Disabled' ) ],
    [ 'td', button_code( 'orange b xs bsn r nf', 'In Progress' ) ],
    [ 'td', button_code( 'red m r5', 'Delete' ) ],
    'plain',
    '.pb30',
    [ 'h2', 'Pagination' ],
    [ 'p', $pages ],
    [ 'p', code( $pages ) ],
    [ 'p', $pages_round ],
    [ 'p', code( $pages_round ) ],
    [ 'p', $pages_split ],
    [ 'p', code( $pages_split ) ],
]);
docs_nav();
get_comp('foot');